"""add location to agent_sessions

Revision ID: 11a161e8331d
Revises: a7ba420606e2
Create Date: 2026-07-10 21:07:14.585061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11a161e8331d'
down_revision: Union[str, Sequence[str], None] = 'a7ba420606e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_sessions', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('agent_sessions', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_sessions', 'longitude')
    op.drop_column('agent_sessions', 'latitude')
    # ### end Alembic commands ###
